name: Python application

on: [push]

jobs:
  test-postgres-14:
    name: Test with PostgreSQL 14.9
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:14.9
        env:
          POSTGRES_USER: decide
          POSTGRES_PASSWORD: decide
          POSTGRES_DB: decide
        ports:
          - 5432:5432
        options: --health-cmd "pg_isready -U decide" --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.10.12
    - name: Install psycopg2 prerequisites
      run: sudo apt-get install -y libpq-dev
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install codacy-coverage
        cp decide/local_settings.gactions.py decide/local_settings.py
    - name: Run tests
      run: |
        cd decide
        coverage run --source=. ./manage.py test --keepdb
        coverage xml

  test-postgres-15:
    name: Test with PostgreSQL 15.0
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:15.0
        env:
          POSTGRES_USER: decide
          POSTGRES_PASSWORD: decide
          POSTGRES_DB: decide
        ports:
          - 5432:5432
        options: --health-cmd "pg_isready -U decide" --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.10.12
    - name: Install psycopg2 prerequisites
      run: sudo apt-get install -y libpq-dev
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install codacy-coverage
        cp decide/local_settings.gactions.py decide/local_settings.py
    - name: Run tests
      run: |
        cd decide
        coverage run --source=. ./manage.py test --keepdb
        coverage xml
